/// Input Event Hierarchy
///
/// Abstract input events generated by virtual controls.
/// These are sent over WebRTC DataChannel to the remote endpoint.
library;

// ============================================================================
// Base Input Event
// ============================================================================

/// Abstract base class for all input events
sealed class InputEvent {
  const InputEvent();
}

// ============================================================================
// Keyboard Events
// ============================================================================

/// Keyboard key press/release event
class KeyboardInputEvent extends InputEvent {
  const KeyboardInputEvent({
    required this.key,
    required this.isDown,
    this.modifiers = const [],
  });

  /// Create a key down event
  factory KeyboardInputEvent.down(String key,
      [List<String> modifiers = const []]) {
    return KeyboardInputEvent(key: key, isDown: true, modifiers: modifiers);
  }

  /// Create a key up event
  factory KeyboardInputEvent.up(String key,
      [List<String> modifiers = const []]) {
    return KeyboardInputEvent(key: key, isDown: false, modifiers: modifiers);
  }
  final String key;
  final bool isDown;
  final List<String> modifiers;

  @override
  String toString() =>
      'KeyboardInputEvent($key, ${isDown ? "down" : "up"}, mods: $modifiers)';
}

// ============================================================================
// Mouse Button Events
// ============================================================================

/// Mouse button press/release event
class MouseButtonInputEvent extends InputEvent {
  const MouseButtonInputEvent({
    required this.button,
    required this.isDown,
  });

  /// Create a mouse button down event
  factory MouseButtonInputEvent.down(String button) {
    return MouseButtonInputEvent(button: button, isDown: true);
  }

  /// Create a mouse button up event
  factory MouseButtonInputEvent.up(String button) {
    return MouseButtonInputEvent(button: button, isDown: false);
  }
  final String button; // left, right, middle
  final bool isDown;

  @override
  String toString() =>
      'MouseButtonInputEvent($button, ${isDown ? "down" : "up"})';
}

// ============================================================================
// Mouse Wheel Events
// ============================================================================

/// Mouse wheel scroll event
class MouseWheelInputEvent extends InputEvent {
  const MouseWheelInputEvent({
    required this.direction,
    required this.delta,
  });

  /// Create a scroll up event
  factory MouseWheelInputEvent.up([int delta = 3]) {
    return MouseWheelInputEvent(direction: 'up', delta: delta);
  }

  /// Create a scroll down event
  factory MouseWheelInputEvent.down([int delta = 3]) {
    return MouseWheelInputEvent(direction: 'down', delta: delta);
  }
  final String direction; // up, down
  final int delta;

  @override
  String toString() => 'MouseWheelInputEvent($direction, delta: $delta)';
}

/// High-resolution mouse wheel scroll event (vector).
///
/// Use when you want smooth scrolling and/or horizontal scrolling.
/// Positive `dy` means scroll down; negative `dy` means scroll up.
class MouseWheelVectorInputEvent extends InputEvent {
  const MouseWheelVectorInputEvent({
    required this.dx,
    required this.dy,
  });

  final double dx;
  final double dy;

  @override
  String toString() => 'MouseWheelVectorInputEvent(dx: $dx, dy: $dy)';
}

// ============================================================================
// Macro Events
// ============================================================================

/// A sequence of input events with timing
class MacroInputEvent extends InputEvent {
  const MacroInputEvent({
    required this.sequence,
  });
  final List<TimedInputEvent> sequence;

  @override
  String toString() => 'MacroInputEvent(${sequence.length} steps)';
}

/// Single input event with delay
class TimedInputEvent {
  const TimedInputEvent({
    required this.event,
    this.delay = Duration.zero,
  });
  final InputEvent event;
  final Duration delay;
}

// ============================================================================
// Joystick Events
// ============================================================================

/// Joystick state change event
class JoystickInputEvent extends InputEvent {
  // Currently active direction keys

  const JoystickInputEvent({
    required this.dx,
    required this.dy,
    required this.activeKeys,
  });
  final double dx; // -1.0 to 1.0
  final double dy; // -1.0 to 1.0
  final List<String> activeKeys;

  @override
  String toString() =>
      'JoystickInputEvent(dx: $dx, dy: $dy, keys: $activeKeys)';
}

// ============================================================================
// Gamepad Events
// ============================================================================

/// Gamepad button press/release event
class GamepadButtonInputEvent extends InputEvent {
  const GamepadButtonInputEvent({
    required this.button,
    required this.isDown,
  });

  factory GamepadButtonInputEvent.down(String button) =>
      GamepadButtonInputEvent(button: button, isDown: true);

  factory GamepadButtonInputEvent.up(String button) =>
      GamepadButtonInputEvent(button: button, isDown: false);
  final String button;
  final bool isDown;

  @override
  String toString() =>
      'GamepadButtonInputEvent($button, ${isDown ? "down" : "up"})';
}

/// Gamepad axis/joystick move event
class GamepadAxisInputEvent extends InputEvent {
  const GamepadAxisInputEvent({
    required this.axisId,
    required this.x,
    required this.y,
  });
  final String axisId; // left, right
  final double x;
  final double y;

  @override
  String toString() => 'GamepadAxisInputEvent($axisId, x: $x, y: $y)';
}

// ============================================================================
// Custom Events
// ============================================================================

/// Custom input event for user-defined actions
class CustomInputEvent extends InputEvent {
  const CustomInputEvent({
    required this.id,
    this.data = const {},
  });
  final String id;
  final Map<String, dynamic> data;

  @override
  String toString() => 'CustomInputEvent($id, data: $data)';
}
