/// Virtual Controller Overlay Widget
///
/// Renders virtual controls as an overlay.
/// Handles touch input and generates InputEvents.
library;

import 'package:flutter/material.dart';
import '../models/virtual_controller_models.dart';
import '../models/input_event.dart';
import 'controls/joystick_widget.dart';
import 'controls/dpad_widget.dart';
import 'controls/key_widget.dart';
import 'controls/button_widget.dart';
import 'controls/mouse_button_widget.dart';
import 'controls/mouse_wheel_widget.dart';
import 'controls/split_mouse_widget.dart';
import 'controls/scroll_stick_widget.dart';
import 'controls/custom_widget.dart';
import 'shared/default_control_widget.dart';
import '../utils/control_geometry.dart';

/// Overlay widget that renders all virtual controls.
class VirtualControllerOverlay extends StatefulWidget {
  /// Creates a virtual controller overlay.
  const VirtualControllerOverlay({
    super.key,
    required this.layout,
    required this.onInputEvent,
    this.opacity = 0.5,
    this.showLabels = true,
  });

  /// The layout configuration containing all controls.
  final VirtualControllerLayout layout;

  /// Callback for input events generated by controls.
  final void Function(InputEvent event) onInputEvent;

  /// Global opacity for the overlay.
  final double opacity;

  /// Whether to show labels on controls.
  final bool showLabels;

  @override
  State<VirtualControllerOverlay> createState() =>
      _VirtualControllerOverlayState();
}

class _VirtualControllerOverlayState extends State<VirtualControllerOverlay> {
  // Performance: Cache expanded controls to avoid recalculation on every build
  List<VirtualControl> _expandedControls = [];
  Size _lastScreenSize = Size.zero;

  @override
  void didUpdateWidget(VirtualControllerOverlay oldWidget) {
    super.didUpdateWidget(oldWidget);
    // Re-expand if layout changed
    if (oldWidget.layout != widget.layout) {
      _expandedControls.clear();
      _lastScreenSize = Size.zero;
    }
  }

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final screenSize = Size(constraints.maxWidth, constraints.maxHeight);

        // Performance: Only re-expand if screen size changed or cache is empty
        if (screenSize != _lastScreenSize || _expandedControls.isEmpty) {
          _expandedControls =
              _expandControls(widget.layout.controls, screenSize);
          _lastScreenSize = screenSize;
        }

        return Stack(
          children: [
            for (final control in _expandedControls)
              _buildPositionedControl(control, screenSize),
          ],
        );
      },
    );
  }

  /// Expand key clusters into individual keys.
  List<VirtualControl> _expandControls(
      List<VirtualControl> controls, Size screenSize) {
    final expanded = <VirtualControl>[];
    for (final control in controls) {
      if (control is VirtualKeyCluster) {
        expanded.addAll(control.expandToKeys(screenSize));
      } else {
        expanded.add(control);
      }
    }
    return expanded;
  }

  Widget _buildPositionedControl(VirtualControl control, Size screenSize) {
    final rect = ControlGeometry.occupiedRect(control, screenSize);
    final controlOpacity = _opacityFrom(control);

    return Positioned(
      left: rect.left,
      top: rect.top,
      width: rect.width,
      height: rect.height,
      child: Opacity(
        opacity: (widget.opacity * controlOpacity).clamp(0.0, 1.0),
        child: _buildControlWidget(control),
      ),
    );
  }

  Widget _buildControlWidget(VirtualControl control) {
    return switch (control) {
      VirtualJoystick c => VirtualJoystickWidget(
          control: c,
          onInputEvent: widget.onInputEvent,
        ),
      VirtualDpad c => VirtualDpadWidget(
          control: c,
          onInputEvent: widget.onInputEvent,
        ),
      VirtualKey c => VirtualKeyWidget(
          control: c,
          onInputEvent: widget.onInputEvent,
          showLabel: widget.showLabels,
        ),
      VirtualMouseButton c => VirtualMouseButtonWidget(
          control: c,
          onInputEvent: widget.onInputEvent,
          showLabel: widget.showLabels,
        ),
      VirtualMouseWheel c => VirtualMouseWheelWidget(
          control: c,
          onInputEvent: widget.onInputEvent,
        ),
      VirtualSplitMouse c => VirtualSplitMouseWidget(
          control: c,
          onInputEvent: widget.onInputEvent,
        ),
      VirtualScrollStick c => VirtualScrollStickWidget(
          control: c,
          onInputEvent: widget.onInputEvent,
        ),
      VirtualButton c => VirtualButtonWidget(
          control: c,
          onInputEvent: widget.onInputEvent,
          showLabel: widget.showLabels,
        ),
      VirtualCustomControl c => VirtualCustomWidget(
          control: c,
          onInputEvent: widget.onInputEvent,
          showLabel: widget.showLabels,
        ),
      _ => DefaultControlWidget(control: control),
    };
  }
}

double _opacityFrom(VirtualControl control) {
  final v = control.config['opacity'];
  if (v is num) return v.toDouble().clamp(0.0, 1.0);
  return 1.0;
}
